/**
 * Authentication architecture (intended production shape)
 * -------------------------------------------------------
 * 1. An Amazon Cognito User Pool is provisioned by the CDK app in `/infra`
 *    (Phase 7). The pool is configured with Google as a federated OIDC
 *    identity provider. Google client ID/secret are CDK context parameters,
 *    created in Google Cloud Console — they are not generated by this app.
 *
 * 2. Cognito Hosted UI / OAuth endpoints are the only identity endpoints this
 *    Next.js app talks to. Shoppers never complete a Google OAuth handshake
 *    directly with Google from TravelLTK; Cognito does that.
 *
 * 3. Auth.js (NextAuth) is configured with the Cognito provider, pointed at
 *    the User Pool's issuer (`https://cognito-idp.{region}.amazonaws.com/{id}`)
 *    and app client. Authorization params set `identity_provider=Google` so
 *    the Hosted UI skips its own form and federates straight to Google.
 *
 * 4. Cognito issues the actual tokens (authorization code → tokens). Auth.js
 *    stores a JWT session in a cookie. The JWT callback upserts
 *    `{ id, email, name, avatarUrl, cognitoSub }` through `upsertUser()`,
 *    which today hits a Next.js route and will call the AWS HTTP API in Phase 7.
 *
 * Required env (configured on AWS + Google Cloud Console, copied into Vercel):
 *   COGNITO_USER_POOL_ID, COGNITO_CLIENT_ID, COGNITO_CLIENT_SECRET,
 *   COGNITO_DOMAIN, COGNITO_REGION, COGNITO_ISSUER, AUTH_SECRET,
 *   GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET (documented here; live values
 *   belong on the Cognito IdP, not in Auth.js).
 */
import NextAuth from "next-auth";
import Cognito from "next-auth/providers/cognito";
import { env, isAuthConfigured } from "@/lib/config";
import { upsertUser } from "@/lib/users";

const cognitoProvider = Cognito({
  clientId: env.COGNITO_CLIENT_ID ?? "unconfigured",
  clientSecret: env.COGNITO_CLIENT_SECRET ?? "unconfigured",
  issuer:
    env.COGNITO_ISSUER ??
    `https://cognito-idp.${env.COGNITO_REGION}.amazonaws.com/${env.COGNITO_USER_POOL_ID ?? "unconfigured"}`,
  authorization: {
    params: {
      identity_provider: "Google",
      scope: "openid email profile",
    },
  },
});

export const { handlers, auth, signIn, signOut } = NextAuth({
  trustHost: true,
  secret: env.AUTH_SECRET ?? "dev-only-replace-with-AUTH_SECRET",
  session: { strategy: "jwt" },
  providers: isAuthConfigured ? [cognitoProvider] : [],
  pages: {
    signIn: "/login",
  },
  callbacks: {
    async jwt({ token, account, profile, user }) {
      if (account) {
        const cognitoSub =
          (profile as { sub?: string } | undefined)?.sub ??
          account.providerAccountId;
        const email =
          (profile as { email?: string } | undefined)?.email ??
          user?.email ??
          token.email;
        const name =
          (profile as { name?: string } | undefined)?.name ??
          user?.name ??
          token.name;
        const avatarUrl =
          (profile as { picture?: string } | undefined)?.picture ??
          user?.image ??
          (typeof token.picture === "string" ? token.picture : null);

        token.cognitoSub = cognitoSub;
        token.picture = avatarUrl;

        if (email && cognitoSub) {
          const record = await upsertUser({
            email,
            name: name ?? email,
            avatarUrl: avatarUrl ?? null,
            cognitoSub,
          });
          token.userId = record.id;
        }
      }
      return token;
    },
    async session({ session, token }) {
      if (session.user) {
        session.user.id = (token.userId as string) ?? (token.sub as string);
        session.user.cognitoSub = token.cognitoSub as string | undefined;
        if (typeof token.picture === "string") {
          session.user.image = token.picture;
        }
      }
      return session;
    },
  },
});
