import { unsplash } from "@/lib/images";
import type { CreatorProfile, Trip, TripDay, TripLeg, User } from "@/types";

export const CONFIRMED_CREATOR_HANDLES = [
  "eileengu",
  "galavantingchristine",
] as const;

export type ConfirmedCreatorHandle = (typeof CONFIRMED_CREATOR_HANDLES)[number];

export function isConfirmedCreatorHandle(handle: string): boolean {
  return CONFIRMED_CREATOR_HANDLES.includes(
    handle.toLowerCase() as ConfirmedCreatorHandle,
  );
}

function leg(
  partial: Omit<TripLeg, "includedInTrip" | "bookingUrl" | "bookingApiRef"> &
    Partial<Pick<TripLeg, "includedInTrip" | "bookingUrl" | "bookingApiRef">>,
): TripLeg {
  return {
    includedInTrip: true,
    bookingUrl: null,
    bookingApiRef: null,
    ...partial,
  };
}

const CHRISTINE_COVER = "/images/creators/christine-dz8c-home.jpg";
const EILEEN_COVER = "/images/creators/3965012587151108160_396557061.jpg";

export const confirmedUsers: User[] = [
  {
    id: "user-creator-eileen",
    email: "eileen@travelltk.com",
    name: "Eileen Gu",
    avatarUrl: EILEEN_COVER,
    cognitoSub: "cognito-sub-eileen",
    role: "creator",
    createdAt: "2025-09-01T12:00:00.000Z",
    updatedAt: "2026-08-20T12:00:00.000Z",
  },
  {
    id: "user-creator-christine",
    email: "christine@travelltk.com",
    name: "Christine Drinan",
    avatarUrl: CHRISTINE_COVER,
    cognitoSub: "cognito-sub-christine",
    role: "creator",
    createdAt: "2025-09-01T12:00:00.000Z",
    updatedAt: "2026-08-20T12:00:00.000Z",
  },
];

export const confirmedCreators: CreatorProfile[] = [
  {
    id: "creator-eileen",
    userId: "user-creator-eileen",
    handle: "eileengu",
    displayName: "Eileen Gu",
    bio: "Olympic alpine, couture fittings, and the itinerary after the podium. The rooms, the mountain, and the table are already chosen.",
    avatarUrl: EILEEN_COVER,
    coverImageUrl: EILEEN_COVER,
    followerCount: 2_400_000,
    verified: true,
    socials: {
      instagram: "https://www.instagram.com/eileengu/",
    },
    categories: ["ski", "luxury", "city-break"],
    createdAt: "2025-09-01T12:00:00.000Z",
  },
  {
    id: "creator-christine",
    userId: "user-creator-christine",
    handle: "galavantingchristine",
    displayName: "Christine Drinan",
    bio: "Founder of Galavante. 140 countries, a thousand hotels, and the working-jet-set itinerary written so you can actually book it.",
    avatarUrl: CHRISTINE_COVER,
    coverImageUrl: CHRISTINE_COVER,
    followerCount: 19_000,
    verified: true,
    socials: {
      instagram: "https://www.instagram.com/galavantingchristine/",
      website: "https://galavante.com/",
    },
    categories: ["luxury", "adventure", "honeymoon"],
    createdAt: "2025-09-01T12:00:00.000Z",
  },
];

const EILEEN_ALPS_DAYS: TripDay[] = [
  {
    dayNumber: 1,
    title: "Geneva to Courchevel 1850",
    location: "Courchevel, France",
    summary:
      "Morning arrival into GVA, private transfer up the valley, and a late lunch in the hotel so the first run is tomorrow, not today.",
    legs: [
      leg({
        id: "leg-eileen-alps-1-flight",
        tripId: "trip-eileen-courchevel",
        dayNumber: 1,
        type: "flight",
        title: "Arrival into Geneva",
        description: "Land before noon. Ski bag through, then a waiting transfer — not a rental car in ice.",
        supplierName: "Swiss",
        supplierRef: "LX-GVA",
        priceEstimateUsd: 920,
        startTime: "10:15",
        endTime: "11:40",
        location: "GVA",
        includedInTrip: false,
        bookingUrl: "https://www.swiss.com/",
      }),
      leg({
        id: "leg-eileen-alps-1-transfer",
        tripId: "trip-eileen-courchevel",
        dayNumber: 1,
        type: "transport",
        title: "Private transfer to Courchevel 1850",
        description: "Two and a half hours in winter. Request a split ski-bag vehicle.",
        supplierName: "Alpine Private Transfers",
        supplierRef: "TRN-CVE-1850",
        priceEstimateUsd: 420,
        startTime: "12:15",
        endTime: "15:00",
        location: "Geneva → Courchevel",
      }),
      leg({
        id: "leg-eileen-alps-1-hotel",
        tripId: "trip-eileen-courchevel",
        dayNumber: 1,
        type: "hotel",
        title: "Aman Le Mélézin",
        description:
          "Ski-in rooms on the Bellecôte. Ask for a mountain-side suite and a late spa slot the first evening.",
        supplierName: "Aman Le Mélézin",
        supplierRef: "HTL-AMAN-CVE",
        priceEstimateUsd: 2100,
        startTime: "15:00",
        endTime: null,
        location: "Courchevel 1850",
        bookingUrl: "https://www.aman.com/hotels/aman-le-melezin",
      }),
    ],
  },
  {
    dayNumber: 2,
    title: "Bellecôte first, Saulire second",
    location: "Courchevel, France",
    summary: "A guide who already has the snow report. No queue at the first lift, long lunch, early finish.",
    legs: [
      leg({
        id: "leg-eileen-alps-2-ski",
        tripId: "trip-eileen-courchevel",
        dayNumber: 2,
        type: "activity",
        title: "Private mountain guide, Three Valleys",
        description: "Half-day, 8:30 start. Off-piste only if the report is clean; otherwise the hidden pistes above La Tania.",
        supplierName: "ESF Courchevel 1850",
        supplierRef: "ACT-ESF-GUIDE",
        priceEstimateUsd: 480,
        startTime: "08:30",
        endTime: "12:30",
        location: "Courchevel",
      }),
      leg({
        id: "leg-eileen-alps-2-lunch",
        tripId: "trip-eileen-courchevel",
        dayNumber: 2,
        type: "restaurant",
        title: "Lunch at Le Chalet de Pierres",
        description: "On-mountain, reserved 13:00. Sit outside if the wind is down.",
        supplierName: "Le Chalet de Pierres",
        supplierRef: "RST-PIERRES",
        priceEstimateUsd: 95,
        startTime: "13:00",
        endTime: "14:30",
        location: "Courchevel",
        includedInTrip: false,
        bookingUrl: "https://www.lechaletdepierres.com/",
      }),
    ],
  },
  {
    dayNumber: 3,
    title: "Rest the knees, keep the altitude",
    location: "Courchevel, France",
    summary: "Spa morning, a fittings call in the afternoon, dinner in the village not the hotel.",
    legs: [
      leg({
        id: "leg-eileen-alps-3-spa",
        tripId: "trip-eileen-courchevel",
        dayNumber: 3,
        type: "activity",
        title: "Aman spa — altitude recovery",
        description: "Ninety minutes. No treatments that keep you off snow tomorrow.",
        supplierName: "Aman Le Mélézin Spa",
        supplierRef: "ACT-AMAN-SPA",
        priceEstimateUsd: 320,
        startTime: "10:00",
        endTime: "11:30",
        location: "Courchevel 1850",
      }),
      leg({
        id: "leg-eileen-alps-3-dinner",
        tripId: "trip-eileen-courchevel",
        dayNumber: 3,
        type: "restaurant",
        title: "Dinner at Le 1947",
        description: "Two Michelin stars, 19:30. The tasting menu, not the à la carte, on a rest day.",
        supplierName: "Le 1947 at Cheval Blanc",
        supplierRef: "RST-1947",
        priceEstimateUsd: 420,
        startTime: "19:30",
        endTime: null,
        location: "Courchevel 1850",
        includedInTrip: false,
        bookingUrl: "https://www.chevalblanc.com/en/maison/courchevel/",
      }),
    ],
  },
  {
    dayNumber: 4,
    title: "Val Thorens high and home",
    location: "Les Trois Vallées, France",
    summary: "The highest skiing in the Three Valleys, then ski home to the hotel door.",
    legs: [
      leg({
        id: "leg-eileen-alps-4-ski",
        tripId: "trip-eileen-courchevel",
        dayNumber: 4,
        type: "activity",
        title: "Guided day to Val Thorens",
        description: "Leave 8:15. Picnic in the pack, not a long lunch, so you ski the afternoon light back to 1850.",
        supplierName: "ESF Courchevel 1850",
        supplierRef: "ACT-ESF-VT",
        priceEstimateUsd: 480,
        startTime: "08:15",
        endTime: "16:00",
        location: "Val Thorens",
      }),
    ],
  },
  {
    dayNumber: 5,
    title: "Last morning, Lyon overnight",
    location: "Lyon, France",
    summary: "One more descent, checkout at noon, transfer to Lyon for the evening flight window.",
    legs: [
      leg({
        id: "leg-eileen-alps-5-hotel",
        tripId: "trip-eileen-courchevel",
        dayNumber: 5,
        type: "hotel",
        title: "InterContinental Lyon - Hotel Dieu",
        description: "One night on the Rhône so the Geneva weather does not own the departure.",
        supplierName: "InterContinental Lyon",
        supplierRef: "HTL-IC-LYS",
        priceEstimateUsd: 380,
        startTime: "16:00",
        endTime: null,
        location: "Lyon",
        bookingUrl: "https://lyon.intercontinental.com/",
      }),
    ],
  },
];

const EILEEN_RIVIERA_DAYS: TripDay[] = [
  {
    dayNumber: 1,
    title: "Nice, then Cap d'Antibes",
    location: "Antibes, France",
    summary: "Afternoon landing, a slow drive along the coast, dinner facing the water not the lobby.",
    legs: [
      leg({
        id: "leg-eileen-riviera-1-flight",
        tripId: "trip-eileen-yacht",
        dayNumber: 1,
        type: "flight",
        title: "Arrival into Nice Côte d'Azur",
        description: "Prefer the afternoon bank. Bags first, then the coast road, not the motorway.",
        supplierName: "Air France",
        supplierRef: "AF-NCE",
        priceEstimateUsd: 640,
        startTime: "14:20",
        endTime: "16:05",
        location: "NCE",
        includedInTrip: false,
        bookingUrl: "https://www.airfrance.com/",
      }),
      leg({
        id: "leg-eileen-riviera-1-hotel",
        tripId: "trip-eileen-yacht",
        dayNumber: 1,
        type: "hotel",
        title: "Hôtel du Cap-Eden-Roc",
        description: "Garden rooms over the sea. Request a cabana for the yacht morning so you never queue for a lounger.",
        supplierName: "Hôtel du Cap-Eden-Roc",
        supplierRef: "HTL-EDEN-ROC",
        priceEstimateUsd: 1850,
        startTime: "17:00",
        endTime: null,
        location: "Cap d'Antibes",
        bookingUrl: "https://www.oetkercollection.com/hotels/hotel-du-cap-eden-roc/",
      }),
    ],
  },
  {
    dayNumber: 2,
    title: "Yacht day, Antibes to the islands",
    location: "Côte d'Azur, France",
    summary: "The day from the reel: leave the pier early, swim off the stern, lunch on deck, back before the light goes gold.",
    legs: [
      leg({
        id: "leg-eileen-riviera-2-yacht",
        tripId: "trip-eileen-yacht",
        dayNumber: 2,
        type: "activity",
        title: "Private day yacht from Port Vauban",
        description: "Skipper plus deckhand. Île Sainte-Marguerite for the swim, then a slow return along the Cap.",
        supplierName: "Antibes Yacht Charter",
        supplierRef: "ACT-YACHT-ANT",
        priceEstimateUsd: 4200,
        startTime: "09:00",
        endTime: "17:00",
        location: "Port Vauban",
      }),
    ],
  },
  {
    dayNumber: 3,
    title: "Èze and the corniche",
    location: "Èze, France",
    summary: "A village morning, not a shopping circuit. The garden at the top, then lunch with a drop to the sea.",
    legs: [
      leg({
        id: "leg-eileen-riviera-3-act",
        tripId: "trip-eileen-yacht",
        dayNumber: 3,
        type: "activity",
        title: "Jardin Exotique d'Èze",
        description: "Arrive at opening. The view is the point; twenty minutes is enough.",
        supplierName: "Jardin Exotique d'Èze",
        supplierRef: "ACT-EZE",
        priceEstimateUsd: 12,
        startTime: "09:00",
        endTime: "10:00",
        location: "Èze",
      }),
      leg({
        id: "leg-eileen-riviera-3-lunch",
        tripId: "trip-eileen-yacht",
        dayNumber: 3,
        type: "restaurant",
        title: "La Chèvre d'Or",
        description: "Terrace if the mistral is quiet. The tasting lunch, then the drive back along the Moyenne Corniche.",
        supplierName: "La Chèvre d'Or",
        supplierRef: "RST-CHEVRE",
        priceEstimateUsd: 210,
        startTime: "12:30",
        endTime: "15:00",
        location: "Èze",
        includedInTrip: false,
        bookingUrl: "https://www.chevredor.com/",
      }),
    ],
  },
  {
    dayNumber: 4,
    title: "One more swim, then Nice",
    location: "Nice, France",
    summary: "Late checkout, a last swim off the rocks, evening in Vieux Nice instead of another hotel dinner.",
    legs: [
      leg({
        id: "leg-eileen-riviera-4-hotel",
        tripId: "trip-eileen-yacht",
        dayNumber: 4,
        type: "hotel",
        title: "Hôtel du Couvent",
        description: "A restored convent in the old town. One night so the morning flight is a taxi, not a coast drive.",
        supplierName: "Hôtel du Couvent",
        supplierRef: "HTL-COUVENT-NCE",
        priceEstimateUsd: 720,
        startTime: "16:00",
        endTime: null,
        location: "Nice",
        bookingUrl: "https://www.hotelducouvent.com/",
      }),
    ],
  },
];

const CHRISTINE_AMALFI_DAYS: TripDay[] = [
  {
    dayNumber: 1,
    title: "Naples to Positano",
    location: "Positano, Italy",
    summary: "Land in the morning, private transfer along the coast, check in before the day-trip boats arrive.",
    legs: [
      leg({
        id: "leg-christine-amalfi-1-flight",
        tripId: "trip-christine-amalfi",
        dayNumber: 1,
        type: "flight",
        title: "Arrival into Naples",
        description: "Morning bank. Skip the ferry on day one — the drive is the introduction.",
        supplierName: "ITA Airways",
        supplierRef: "AZ-NAP",
        priceEstimateUsd: 540,
        startTime: "09:40",
        endTime: "11:20",
        location: "NAP",
        includedInTrip: false,
        bookingUrl: "https://www.ita-airways.com/",
      }),
      leg({
        id: "leg-christine-amalfi-1-transfer",
        tripId: "trip-christine-amalfi",
        dayNumber: 1,
        type: "transport",
        title: "Private transfer to Positano",
        description: "Ninety minutes if the coast is kind. Sit on the water side.",
        supplierName: "Amalfi Private Drivers",
        supplierRef: "TRN-NAP-POS",
        priceEstimateUsd: 280,
        startTime: "12:00",
        endTime: "13:45",
        location: "Naples → Positano",
      }),
      leg({
        id: "leg-christine-amalfi-1-hotel",
        tripId: "trip-christine-amalfi",
        dayNumber: 1,
        type: "hotel",
        title: "Le Sirenuse",
        description: "A room with the sea, not the street. Franco's Bar at dusk, not a second restaurant.",
        supplierName: "Le Sirenuse",
        supplierRef: "HTL-SIRENUSE",
        priceEstimateUsd: 1650,
        startTime: "14:00",
        endTime: null,
        location: "Positano",
        bookingUrl: "https://www.sirenuse.it/",
      }),
    ],
  },
  {
    dayNumber: 2,
    title: "Positano on foot, then the water",
    location: "Positano, Italy",
    summary: "Church steps before the heat, a boat after lunch, back for the hotel pool when the town fills.",
    legs: [
      leg({
        id: "leg-christine-amalfi-2-boat",
        tripId: "trip-christine-amalfi",
        dayNumber: 2,
        type: "activity",
        title: "Private gozzo to Li Galli",
        description: "Leave 11:00. Swim, no landing. The captain already knows which cove is quiet that day.",
        supplierName: "Positano Boat Service",
        supplierRef: "ACT-GOZZO",
        priceEstimateUsd: 650,
        startTime: "11:00",
        endTime: "16:00",
        location: "Positano",
      }),
      leg({
        id: "leg-christine-amalfi-2-dinner",
        tripId: "trip-christine-amalfi",
        dayNumber: 2,
        type: "restaurant",
        title: "Dinner at La Sponda",
        description: "In-house, 20:30. The candlelit room, not the terrace, if the wind is up.",
        supplierName: "La Sponda",
        supplierRef: "RST-SPONDA",
        priceEstimateUsd: 180,
        startTime: "20:30",
        endTime: null,
        location: "Positano",
      }),
    ],
  },
  {
    dayNumber: 3,
    title: "Capri, overnight",
    location: "Capri, Italy",
    summary: "Hydrofoil after breakfast. The island is a night, not a day trip from Positano.",
    legs: [
      leg({
        id: "leg-christine-amalfi-3-ferry",
        tripId: "trip-christine-amalfi",
        dayNumber: 3,
        type: "transport",
        title: "Hydrofoil Positano to Capri",
        description: "Alicost morning sailing. Bags with the porter at Marina Grande.",
        supplierName: "Alicost",
        supplierRef: "TRN-ALICOST",
        priceEstimateUsd: 45,
        startTime: "09:25",
        endTime: "10:10",
        location: "Positano → Capri",
      }),
      leg({
        id: "leg-christine-amalfi-3-hotel",
        tripId: "trip-christine-amalfi",
        dayNumber: 3,
        type: "hotel",
        title: "JK Place Capri",
        description: "Marina Grande side, so you are not climbing to Anacapri with luggage. The pool faces the right water.",
        supplierName: "JK Place Capri",
        supplierRef: "HTL-JK-CAPRI",
        priceEstimateUsd: 1400,
        startTime: "14:00",
        endTime: null,
        location: "Capri",
        bookingUrl: "https://www.jkcapri.com/",
      }),
    ],
  },
  {
    dayNumber: 4,
    title: "Anacapri and the chairlift",
    location: "Capri, Italy",
    summary: "Monte Solaro in the morning, a long lunch, no Blue Grotto queue.",
    legs: [
      leg({
        id: "leg-christine-amalfi-4-act",
        tripId: "trip-christine-amalfi",
        dayNumber: 4,
        type: "activity",
        title: "Monte Solaro chairlift",
        description: "First cars after opening. Down on foot through Anacapri if the knees allow.",
        supplierName: "Seggiovia Monte Solaro",
        supplierRef: "ACT-SOLARO",
        priceEstimateUsd: 16,
        startTime: "09:30",
        endTime: "11:30",
        location: "Anacapri",
      }),
      leg({
        id: "leg-christine-amalfi-4-lunch",
        tripId: "trip-christine-amalfi",
        dayNumber: 4,
        type: "restaurant",
        title: "Lunch at Il Riccio",
        description: "The terrace over the Grotta Azzurra. Book the sea-view table, not a cave tour.",
        supplierName: "Il Riccio",
        supplierRef: "RST-RICCIO",
        priceEstimateUsd: 140,
        startTime: "13:00",
        endTime: "15:30",
        location: "Anacapri",
        includedInTrip: false,
        bookingUrl: "https://www.capripalace.com/en/il-riccio-restaurant",
      }),
    ],
  },
  {
    dayNumber: 5,
    title: "Ravello for the last night",
    location: "Ravello, Italy",
    summary: "Back to the mainland, up to the quieter town, a garden that is not a cliff restaurant.",
    legs: [
      leg({
        id: "leg-christine-amalfi-5-hotel",
        tripId: "trip-christine-amalfi",
        dayNumber: 5,
        type: "hotel",
        title: "Palazzo Avino",
        description: "A former palazzo above the coast. Request a garden room; the view still finds you.",
        supplierName: "Palazzo Avino",
        supplierRef: "HTL-AVINO",
        priceEstimateUsd: 980,
        startTime: "15:00",
        endTime: null,
        location: "Ravello",
        bookingUrl: "https://www.palazzoavino.com/",
      }),
    ],
  },
  {
    dayNumber: 6,
    title: "Villa Cimbrone, then Naples",
    location: "Ravello, Italy",
    summary: "The Terrace of Infinity at opening, then the drive to NAP with a buffer for the coast traffic.",
    legs: [
      leg({
        id: "leg-christine-amalfi-6-act",
        tripId: "trip-christine-amalfi",
        dayNumber: 6,
        type: "activity",
        title: "Villa Cimbrone gardens",
        description: "Arrive at opening. Thirty minutes on the terrace, then leave before the tour groups.",
        supplierName: "Villa Cimbrone",
        supplierRef: "ACT-CIMBRONE",
        priceEstimateUsd: 10,
        startTime: "09:00",
        endTime: "10:00",
        location: "Ravello",
      }),
    ],
  },
];

const CHRISTINE_ATACAMA_DAYS: TripDay[] = [
  {
    dayNumber: 1,
    title: "Santiago buffer night",
    location: "Santiago, Chile",
    summary: "Do not connect to Calama the same day. The Andes do not care about your itinerary.",
    legs: [
      leg({
        id: "leg-christine-atacama-1-hotel",
        tripId: "trip-christine-atacama",
        dayNumber: 1,
        type: "hotel",
        title: "The Lastarria, Santiago",
        description: "A townhouse in Lastarria. Walk to dinner; the airport run is tomorrow.",
        supplierName: "The Lastarria",
        supplierRef: "HTL-LASTARRIA",
        priceEstimateUsd: 320,
        startTime: "15:00",
        endTime: null,
        location: "Santiago",
        bookingUrl: "https://www.thelastarria.com/",
      }),
      leg({
        id: "leg-christine-atacama-1-dinner",
        tripId: "trip-christine-atacama",
        dayNumber: 1,
        type: "restaurant",
        title: "Dinner at Boragó",
        description: "If you can get the table. Otherwise a neighborhood wine bar — do not force a tasting menu after a long haul.",
        supplierName: "Boragó",
        supplierRef: "RST-BORAGO",
        priceEstimateUsd: 160,
        startTime: "20:00",
        endTime: null,
        location: "Santiago",
        includedInTrip: false,
        bookingUrl: "https://borago.cl/",
      }),
    ],
  },
  {
    dayNumber: 2,
    title: "Into the Atacama",
    location: "San Pedro de Atacama, Chile",
    summary: "Morning hop to Calama, lodge transfer, altitude afternoon with nothing scheduled.",
    legs: [
      leg({
        id: "leg-christine-atacama-2-flight",
        tripId: "trip-christine-atacama",
        dayNumber: 2,
        type: "flight",
        title: "Santiago to Calama",
        description: "Morning LATAM. The lodge meets you; do not self-drive the first day at altitude.",
        supplierName: "LATAM",
        supplierRef: "LA-CJC",
        priceEstimateUsd: 180,
        startTime: "08:10",
        endTime: "10:20",
        location: "SCL → CJC",
      }),
      leg({
        id: "leg-christine-atacama-2-hotel",
        tripId: "trip-christine-atacama",
        dayNumber: 2,
        type: "hotel",
        title: "Tierra Atacama",
        description:
          "Adventure lodge, not a desert tent. Hike hard, sleep well. The outdoor showers face Licancabur.",
        supplierName: "Tierra Atacama",
        supplierRef: "HTL-TIERRA-AT",
        priceEstimateUsd: 890,
        startTime: "13:00",
        endTime: null,
        location: "San Pedro de Atacama",
        bookingUrl: "https://www.tierrahotels.com/tierra-atacama/",
      }),
    ],
  },
  {
    dayNumber: 3,
    title: "Valle de la Luna at the right hour",
    location: "San Pedro de Atacama, Chile",
    summary: "A morning hike while it is cold, a long lunch at the lodge, the valley at last light.",
    legs: [
      leg({
        id: "leg-christine-atacama-3-hike",
        tripId: "trip-christine-atacama",
        dayNumber: 3,
        type: "activity",
        title: "Guided Valle de la Luna at dusk",
        description: "Lodge excursion. Leave mid-afternoon so you are on the ridge for the color, not the tour-bus noon.",
        supplierName: "Tierra Atacama",
        supplierRef: "ACT-LUNA",
        priceEstimateUsd: 0,
        startTime: "15:30",
        endTime: "19:00",
        location: "Valle de la Luna",
      }),
    ],
  },
  {
    dayNumber: 4,
    title: "Geysers and the high plateau",
    location: "El Tatio, Chile",
    summary: "Pre-dawn departure, layers, and a quiet afternoon — this is the altitude day.",
    legs: [
      leg({
        id: "leg-christine-atacama-4-geyser",
        tripId: "trip-christine-atacama",
        dayNumber: 4,
        type: "activity",
        title: "El Tatio geysers at sunrise",
        description: "Lodge vehicle, 4:30 departure. Breakfast after the steam, not before.",
        supplierName: "Tierra Atacama",
        supplierRef: "ACT-TATIO",
        priceEstimateUsd: 0,
        startTime: "04:30",
        endTime: "12:00",
        location: "El Tatio",
      }),
    ],
  },
  {
    dayNumber: 5,
    title: "Stars, then south",
    location: "San Pedro de Atacama, Chile",
    summary: "A last desert morning, observatory if the sky is clear, overnight in Santiago for the long haul.",
    legs: [
      leg({
        id: "leg-christine-atacama-5-stars",
        tripId: "trip-christine-atacama",
        dayNumber: 5,
        type: "activity",
        title: "Lodge astronomy session",
        description: "Only if the forecast is clear. Cancel without guilt — the altitude already did the work.",
        supplierName: "Tierra Atacama",
        supplierRef: "ACT-STARS",
        priceEstimateUsd: 0,
        startTime: "21:00",
        endTime: "22:30",
        location: "San Pedro de Atacama",
      }),
      leg({
        id: "leg-christine-atacama-5-hotel",
        tripId: "trip-christine-atacama",
        dayNumber: 5,
        type: "hotel",
        title: "The Lastarria, Santiago",
        description: "Same townhouse on the way out. Early airport run the next morning.",
        supplierName: "The Lastarria",
        supplierRef: "HTL-LASTARRIA-2",
        priceEstimateUsd: 320,
        startTime: "20:00",
        endTime: null,
        location: "Santiago",
        bookingUrl: "https://www.thelastarria.com/",
      }),
    ],
  },
];

export const confirmedTrips: Trip[] = [
  {
    id: "trip-eileen-courchevel",
    slug: "courchevel-after-the-podium",
    creatorId: "creator-eileen",
    title: "Courchevel after the podium",
    subtitle: "Five nights in 1850 — ski, recover, then ski home to the door",
    description:
      "Eileen's alpine week: Aman Le Mélézin, a guide who already has the snow report, and a Lyon buffer so Geneva weather never owns the departure. The fittings call sits on the rest day, not the first descent.",
    coverImageUrl: unsplash("photo-1551524559-8af4e6624178"),
    destinations: ["Geneva", "Courchevel", "Lyon"],
    category: "ski",
    nights: 5,
    priceFromUsd: 8900,
    bookingFeeUsd: 199,
    currency: "USD",
    status: "published",
    saveCount: 12840,
    bookingCount: 36,
    averageRating: 4.9,
    reviewCount: 14,
    days: EILEEN_ALPS_DAYS,
    createdAt: "2025-12-02T12:00:00.000Z",
    publishedAt: "2026-01-12T12:00:00.000Z",
    seasonLabel: "January 2026",
    videos: [
      {
        id: "vid-eileen-alps-1",
        platform: "instagram",
        title: "First light on the Bellecôte",
        url: "https://www.instagram.com/eileengu/",
        thumbnailUrl: unsplash("photo-1605540436563-5bca919ae766"),
      },
      {
        id: "vid-eileen-alps-2",
        platform: "instagram",
        title: "Ski home to Le Mélézin",
        url: "https://www.instagram.com/eileengu/",
        thumbnailUrl: unsplash("photo-1483728642387-6c3bdd6c93e5"),
      },
    ],
  },
  {
    id: "trip-eileen-yacht",
    slug: "antibes-yacht-week",
    creatorId: "creator-eileen",
    title: "Antibes, a yacht day, then Nice",
    subtitle: "The Côte d'Azur week from the water, not the boardwalk",
    description:
      "The itinerary behind the yacht still: Hôtel du Cap-Eden-Roc, a day boat from Port Vauban, Èze at opening, and a last night in Vieux Nice so the morning flight is a taxi.",
    coverImageUrl: EILEEN_COVER,
    destinations: ["Nice", "Antibes", "Èze"],
    category: "luxury",
    nights: 4,
    priceFromUsd: 12400,
    bookingFeeUsd: 249,
    currency: "USD",
    status: "published",
    saveCount: 22100,
    bookingCount: 18,
    averageRating: 4.8,
    reviewCount: 9,
    days: EILEEN_RIVIERA_DAYS,
    createdAt: "2026-06-04T12:00:00.000Z",
    publishedAt: "2026-07-01T12:00:00.000Z",
    seasonLabel: "July 2026",
    videos: [
      {
        id: "vid-eileen-yacht-1",
        platform: "instagram",
        title: "Yacht morning off Antibes",
        url: "https://www.instagram.com/p/DcGjfDDGChA/",
        thumbnailUrl: EILEEN_COVER,
      },
      {
        id: "vid-eileen-yacht-2",
        platform: "instagram",
        title: "Cap d'Antibes from the water",
        url: "https://www.instagram.com/eileengu/",
        thumbnailUrl: unsplash("photo-1567899378494-47b22a2ae96a"),
      },
    ],
  },
  {
    id: "trip-christine-amalfi",
    slug: "positano-capri-ravello",
    creatorId: "creator-christine",
    title: "Positano, Capri overnight, Ravello last",
    subtitle: "The coast in the order that actually works — not a day-trip loop",
    description:
      "Christine's Amalfi week: Le Sirenuse, a night on Capri so the island is not a cattle-boat, then Palazzo Avino and Villa Cimbrone at opening. The drive from Naples is the introduction; the hydrofoil is day three.",
    coverImageUrl: unsplash("photo-1533106497176-45ae19e68ba2"),
    destinations: ["Positano", "Capri", "Ravello"],
    category: "luxury",
    nights: 6,
    priceFromUsd: 7800,
    bookingFeeUsd: 179,
    currency: "USD",
    status: "published",
    saveCount: 9640,
    bookingCount: 44,
    averageRating: 4.9,
    reviewCount: 21,
    days: CHRISTINE_AMALFI_DAYS,
    createdAt: "2025-08-18T12:00:00.000Z",
    publishedAt: "2025-09-02T12:00:00.000Z",
    seasonLabel: "September 2025",
    videos: [
      {
        id: "vid-christine-amalfi-1",
        platform: "instagram",
        title: "Positano from the gozzo",
        url: "https://www.instagram.com/galavantingchristine/",
        thumbnailUrl: CHRISTINE_COVER,
      },
      {
        id: "vid-christine-amalfi-2",
        platform: "website",
        title: "Galavante notes on the coast",
        url: "https://galavante.com/",
        thumbnailUrl: unsplash("photo-1516483638261-f4dbaf036963"),
      },
    ],
  },
  {
    id: "trip-christine-atacama",
    slug: "atacama-tierra-altitude",
    creatorId: "creator-christine",
    title: "Atacama with a Santiago buffer",
    subtitle: "Tierra Atacama, Valle de la Luna at dusk, El Tatio at 4:30",
    description:
      "A desert week that does not connect through Calama the same day. Lodge excursions, outdoor showers facing Licancabur, and the same Lastarria townhouse on the way in and out.",
    coverImageUrl: unsplash("photo-1473580044384-7ba9967e16a0"),
    destinations: ["Santiago", "San Pedro de Atacama"],
    category: "adventure",
    nights: 5,
    priceFromUsd: 4200,
    bookingFeeUsd: 129,
    currency: "USD",
    status: "published",
    saveCount: 5120,
    bookingCount: 27,
    averageRating: 4.8,
    reviewCount: 12,
    days: CHRISTINE_ATACAMA_DAYS,
    createdAt: "2026-03-01T12:00:00.000Z",
    publishedAt: "2026-03-20T12:00:00.000Z",
    seasonLabel: "March 2026",
    videos: [
      {
        id: "vid-christine-atacama-1",
        platform: "instagram",
        title: "Back in the Atacama",
        url: "https://www.instagram.com/galavantingchristine/",
        thumbnailUrl: unsplash("photo-1469854523086-cc02fe5d8800"),
      },
      {
        id: "vid-christine-atacama-2",
        platform: "website",
        title: "Tierra Atacama, from the notes",
        url: "https://galavante.com/",
        thumbnailUrl: unsplash("photo-1509316785289-025f5b846b35"),
      },
    ],
  },
];
